name: Update README Tree

on:
  push:
    branches:
      - master  # 触发分支改为 master

jobs:
  build:
    runs-on: ubuntu-latest

    # 使用 permissions 替代 SSH 密钥，更安全、更简单
    permissions:
      contents: write # 授予工作流向仓库写入内容的权限

    steps:
      # 步骤 1: 检出你的代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 步骤 2: 使用现成的 Action 生成目录树
      - name: Generate README Tree
        uses: RavelloH/readme-tree@v1.1.0
        with:
          # 核心配置：指定你的开始和结束标记
          start-marker: '<tree start>'
          end-marker: '<tree end>'
          # 忽略不需要出现在目录树中的文件夹
          ignore: '.git,.github,assets'

      # 步骤 3: 提交并推送更改 (安全版本)
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # 添加可能已更改的 README.md 文件
          git add README.md
          # 检查是否有实际更改，避免创建空的 commit
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi