name: Update README Tree

on:
  push:
    branches:
      - master

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 生成目录树
      - name: Generate directory tree
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          # 忽略 .git, .github 和 assets 目录
          tree -I '.git|.github|assets' > tree.md

      # 步骤 3: 更新 README 文件
      - name: Update README.md with new tree
        run: |
          python -c '
          import re
          
          with open("tree.md", "r", encoding="utf-8") as tree_file:
              tree_content = tree_file.read()
          
          with open("README.md", "r+", encoding="utf-8") as f:
              readme_content = f.read()
          
              # 核心修改：严格按照您的要求，使用 <tree start> 和 <tree end> 作为标识符
              # 这个脚本会保留标识符，只更新它们之间的内容
              new_readme_content = re.sub(
                  r"(<tree start>)(.*)(<tree end>)",
                  f"\\1\n\n```\n{tree_content}```\n\n\\3",
                  readme_content,
                  flags=re.DOTALL
              )
          
              f.seek(0)
              f.write(new_readme_content)
              f.truncate()
          '

      # 步骤 4: 设置 SSH 密钥
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      # 步骤 5: 提交并推送更改
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree [skip ci]"
            git remote set-url origin git@github.com:${{ github.repository }}.git
            git push
          else
            echo "No changes to commit."
          fi