name: Update README Tree

on:
  push:
    branches:
      - master

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate directory tree
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          tree -I '.git|.github|assets' > tree.md

      - name: Update README.md with new tree
        run: |
          python -c '
          import re
          
          with open("tree.md", "r", encoding="utf-8") as tree_file:
              tree_content = tree_file.read()
          
          with open("README.md", "r+", encoding="utf-8") as f:
              readme_content = f.read()
          
              # 使用标准的、不可见的 HTML 注释作为标识符
              new_readme_content = re.sub(
                  r"()(.*)()",
                  f"\\1\n```\n{tree_content}```\n\\3",
                  readme_content,
                  flags=re.DOTALL
              )
          
              f.seek(0)
              f.write(new_readme_content)
              f.truncate()
          '

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree [skip ci]"
            git remote set-url origin git@github.com:${{ github.repository }}.git
            git push
          else
            echo "No changes to commit."
          fi