name: Update README Tree

on:
  push:
    branches:
      - master # 或者你的主分支名，如 master

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate directory tree
        run: |
          tree -I '.git|.github' > tree.md

      - name: Update README.md with new tree
        run: |
          python -c '
          import re

          # Open the README file once and perform all operations within this block
          with open("README.md", "r+", encoding="utf-8") as f:
              # 1. Read the original content of README.md
              readme_content = f.read()
              
              # 2. Read the content of the generated tree file
              with open("tree.md", "r", encoding="utf-8") as tree_file:
                  tree_content = tree_file.read()

              # 3. Use regex to find the markers and create the new content
              new_readme_content = re.sub(
                  r"()(.*)()",
                  f"\\1\n```\n{tree_content}```\n\\3",
                  readme_content,
                  flags=re.DOTALL
              )
              
              # 4. Go back to the beginning of the file and write the new content
              f.seek(0)
              f.write(new_readme_content)
              f.truncate()
          '

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree"
            git push
          else
            echo "No changes to commit."
          fi