name: Update README Tree

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 步骤 1: 检出你的代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 步骤 2: 使用现成的 Action 生成目录树
      - name: Generate README Tree
        uses: RavelloH/readme-tree@v1.1.0
        with:
          # --- 核心修正在这里 ---
          # 为标记加上单引号，确保它们被当作纯字符串处理
          start-marker: <treestart>
          end-marker: <treeend>
          # --------------------
          
          # 忽略不需要出现在目录树中的文件夹
          ignore: '.git,.github,assets'

      # 步骤 3: 提交并推送更改 (安全版本)
      - name: Commit and Push Changes
        run: |
          git config --local user.email "zuolan1102@qq.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # 检查是否有实际更改，避免创建空的 commit
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi