name: Update README Tree

on:
  push:
    branches:
      - master # Or your default branch, e.g., master

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate directory tree
        # The -I flag ignores specified directories or files.
        run: |
          tree -I '.git|.github' > tree.md

      - name: Update README.de with new tree
        run: |
          python -c '
          import re

          # Read the README file
          with open("README.md", "r+", encoding="utf-8") as f:
              readme_content = f.read()
          
          # Read the generated tree file
          with open("tree.md", "r", encoding="utf-8") as tree_file:
              tree_content = tree_file.read()

          # Use regex to find the markers and replace the content
          new_readme_content = re.sub(
              r"()(.*)()",
              f"\\1\n```\n{tree_content}```\n\\3",
              readme_content,
              flags=re.DOTALL
          )

          # Write the new content back to the README
          f.seek(0)
          f.write(new_readme_content)
          f.truncate()
          '

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Only commit and push if there are actual changes
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree"
            git push
          else
            echo "No changes to commit."
          fi