name: Update README Tree

on:
  push:
    branches:
      - master

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 生成目录树
      - name: Generate directory tree
        run: |
          tree -I '.git|.github' > tree.md

      # 步骤 3: 更新 README 文件（使用新的标记）
      - name: Update README.md with new tree
        run: |
          python -c '
          import re
          with open("README.md", "r+", encoding="utf-8") as f:
              readme_content = f.read()
              with open("tree.md", "r", encoding="utf-8") as tree_file:
                  tree_content = tree_file.read()
              
              # *** 这里是关键的修改 ***
              # 将正则表达式中的标记替换为您指定的新标记
              new_readme_content = re.sub(
                  r"(<repo tree start>)(.*)(<repo tree end>)",
                  f"\\1\n```\n{tree_content}```\n\\3",
                  readme_content,
                  flags=re.DOTALL
              )
              
              f.seek(0)
              f.write(new_readme_content)
              f.truncate()
          '

      # 步骤 4: 设置 SSH 密钥
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      # 步骤 5: 使用 SSH 提交并推送
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update README tree"
            git remote set-url origin git@github.com:zuoliangyu/NUEDC_TOPIC.git
            git push
          else
            echo "No changes to commit."
          fi